version: "3"

services:
  app:
    image: my-app:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for GUI purposes
      - /home/antoine:/home/antoine
      - /etc/passwd:/etc/passwd # so that the user is found inside the docker
      - /etc/group:/etc/group # so that the group of the user is found inside the docker
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
    user: ${CURRENT_UID} # this env var needs to be exported before running `docker compose up`
    group_add:
      - dialout # so that the user belongs to the `dialout` group, who owns `/dev/ttyACM0`
