# Vehicle parameters
NEUTRAL_STEERING_PWM_CMD = 90
NEUTRAL_THROTTLE_PWM_CMD = 90

# Simulation settings
SIM_FREQUENCY_HZ = 10.0
SIM_TIME_STEP_SECS = 0.1

# Vehicle sim parameters
DESIRED_ACC_GAIN_P = 0.5

# Throttle parameters
THROTTLE_PWM_TO_VELOCITY_MPS_SLOPE = 0.54
THROTTLE_PWM_TO_VELOCITY_MPS_OFFSET = -51.1
