#!/usr/bin/python3

import math
from datetime import datetime, timezone

import constants
import numpy as np
import rospy
import tf
import utm
from dynamic_reconfigure.server import Server
from dynamic_reconfigure_pkg.cfg import vehicle_simConfig
from geometry_msgs.msg import PoseStamped, TwistStamped
from geometry_utils_pkg.geometry_utils import MPS_TO_KNOTS, State
from nmea_msgs.msg import Gprmc
from self_racing_car_msgs.msg import ArduinoLogging
from std_msgs.msg import Float32
from vehicle_sim import LateralModel, LongitudinalModel, VehicleSim


class Sim:
    def __init__(self):
        # Constants
        rate = rospy.get_param("~rate", constants.SIM_FREQUENCY_HZ)

        # Subscribers
        rospy.Subscriber(
            "initialpose",
            PoseStamped,
            self.clicked_point_callback,
        )
        rospy.Subscriber(
            "steering_pwm_cmd",
            Float32,
            self.steering_pwm_cmd_callback,
        )
        rospy.Subscriber(
            "throttle_pwm_cmd",
            Float32,
            self.throttle_pwm_cmd_callback,
        )

        # Publishers
        self.sim_pose_pub = rospy.Publisher(
            "current_pose_sim",
            PoseStamped,
            queue_size=10,
        )
        self.sim_twist_pub = rospy.Publisher(
            "current_velocity_sim",
            TwistStamped,
            queue_size=10,
        )
        self.rmc_pub = rospy.Publisher("gps_info", Gprmc, queue_size=10)
        self.arduino_logging_pub = rospy.Publisher(
            "arduino_logging", ArduinoLogging, queue_size=10
        )

        # Dynamic reconfigure server
        self.dynamic_reconfigure_server = Server(
            vehicle_simConfig,
            self.dynamic_reconfigure_callback,
        )

        # Initialization
        self.simulated_vehicle = VehicleSim(
            lateral_model=LateralModel.PERFECT,
            longitudinal_model=LongitudinalModel.ACC_P_CONTROl,
            wheelbase_m=constants.WHEELBASE_M,
            desired_acc_gain_p=constants.DESIRED_ACC_GAIN_P,
        )

        self.state_initialized = False
        self.tf_listener = tf.TransformListener()
        self.rate = rospy.Rate(rate)
        self.steering_pwm_cmd = constants.NEUTRAL_STEERING_PWM_CMD
        self.throttle_pwm_cmd = constants.NEUTRAL_THROTTLE_PWM_CMD

    def clicked_point_callback(self, msg: PoseStamped):
        """
        Callback function to initialize the position and velocity of simulated vehicle when a clicked_point topic is published
        """

        rospy.logwarn("Clicked point callback")

        # Convert the coordinates from the map to the world frame.
        try:
            (trans, rot) = self.tf_listener.lookupTransform(
                "world", "map", rospy.Time(0)
            )

            orientation_list = [
                msg.pose.orientation.x,
                msg.pose.orientation.y,
                msg.pose.orientation.z,
                msg.pose.orientation.w,
            ]
            (roll, pitch, yaw) = tf.transformations.euler_from_quaternion(
                orientation_list
            )

            # Initialize the position and orientation using the position of the clicked point
            self.simulated_vehicle.current_state.x = msg.pose.position.x + trans[0]
            self.simulated_vehicle.current_state.y = msg.pose.position.y + trans[1]
            self.simulated_vehicle.current_state.angle = yaw

            # Initialize the speed to zero
            self.simulated_vehicle.current_state.vx = 0

            self.state_initialized = True

        except (
            tf.LookupException,
            tf.ConnectivityException,
            tf.ExtrapolationException,
        ):
            rospy.logwarn("Error during coordinate transform")

    def dynamic_reconfigure_callback(self, config, level):
        """
        Dynamic reconfigure callback, to change parameters.

        Args:
            - config (dict): Dictionary containing current values of all reconfigurable parameters
            - level (int): Bitmask used to indicate the level of change
        """
        self.set_arduino_log_engage = config["set_arduino_log_engage"]

        return config

    def steering_pwm_cmd_callback(self, msg: Float32):
        """
        Steering pwm command callback, generated by lateral controller.
        """
        self.steering_pwm_cmd = msg.data

    def throttle_pwm_cmd_callback(self, msg: Float32):
        """
        Throttle pwm command callback, generated by longitudinal controller.
        """
        self.throttle_pwm_cmd = msg.data

    def loop(self):
        """
        Main loop of the vehicle simulator
        """

        while not rospy.is_shutdown():
            # If initial state has not been initialized
            if not self.state_initialized:
                rospy.loginfo("Sim has not started.")

            else:
                # Predict next position given steering input
                self.simulated_vehicle.predict_next_pose_from_steering_pwm_cmd(
                    self.steering_pwm_cmd, constants.SIM_TIME_STEP_SECS
                )

                # Predict next velocity based on throttle input
                self.simulated_vehicle.predict_next_velocity_from_throttle_pwm_cmd(
                    self.throttle_pwm_cmd, constants.SIM_TIME_STEP_SECS
                )

                # Publish current simulated state for debugging
                self.publish_sim_state(self.simulated_vehicle.current_state)

                self.publish_arduino_logging()

                # Publish Gprmc topic
                self.publish_nmea_sentence(self.simulated_vehicle.current_state)

                # Convert position and velocity to NMEA sentence
                # sentence = self.nmea.create_sentence_string_from_state(self.simulated_vehicle.current_state)

                # Publish sentence on serial
                # self.serial_output.write(sentence)

            self.rate.sleep()

    def publish_sim_state(self, current_state: State) -> None:
        """
        Function to publish the vehicle's current position and velocity
        Args:
            - state [State]: Current state of vehicle sim
        """

        """ Current position """
        pose_msg = PoseStamped()
        pose_msg.header.frame_id = "world"
        pose_msg.header.stamp = rospy.Time.now()
        pose_msg.pose.position.x = current_state.x
        pose_msg.pose.position.y = current_state.y

        quaternion = tf.transformations.quaternion_from_euler(0, 0, current_state.angle)
        pose_msg.pose.orientation.x = quaternion[0]
        pose_msg.pose.orientation.y = quaternion[1]
        pose_msg.pose.orientation.z = quaternion[2]
        pose_msg.pose.orientation.w = quaternion[3]

        self.sim_pose_pub.publish(pose_msg)

        """ Current velocity """
        twist_msg = TwistStamped()
        twist_msg.header.frame_id = "world"
        twist_msg.header.stamp = rospy.Time.now()
        twist_msg.twist.linear.x = current_state.vx

        self.sim_twist_pub.publish(twist_msg)

    def publish_nmea_sentence(self, current_state: State):
        """
        Function to publish the topic Gprmc topic
        Args:
            - state [State]: Current state of vehicle sim
        """

        # Compute latitude and longitude from UTM coordinates
        zone_number = 10
        zone_letter = "S"
        latitude, longitude = utm.to_latlon(
            current_state.x, current_state.y, zone_number, zone_letter
        )

        # Current time
        now = datetime.now(timezone.utc)
        utc_seconds = now.second + now.microsecond / 1000000
        date = "%s-%s-%s" % (now.year, now.month, now.day)

        # Track angle
        track_angle_deg = ((math.pi / 2) - current_state.angle) * 180 / np.pi

        # Speed
        speed_knots = current_state.vx * MPS_TO_KNOTS

        msg = Gprmc()
        msg.header.stamp = rospy.Time.now()
        msg.utc_seconds = utc_seconds
        msg.lat = latitude
        msg.lon = longitude
        msg.lat_dir = "N"
        msg.lon_dir = "W"
        msg.speed = speed_knots
        msg.track = track_angle_deg
        msg.date = date
        msg.mag_var = -1
        msg.mag_var_direction = ""
        msg.mode_indicator = "A"

        self.rmc_pub.publish(msg)

    def publish_arduino_logging(self):
        """
        Function to publish the topic /arduino_logging.
        At the moment we just populate the engaged_mode field.
        """

        arduino_logging_msg = ArduinoLogging()

        arduino_logging_msg.engaged_mode = self.set_arduino_log_engage

        self.arduino_logging_pub.publish(arduino_logging_msg)


if __name__ == "__main__":
    try:
        rospy.init_node("sim")
        sim = Sim()
        sim.loop()
    except rospy.ROSInterruptException:
        rospy.logwarn("ROS interrupted. Stopping simulation.")
